[project]
name = "mini-vec2vec"
version = "0.1.1"
description = "Python implementation of the mini-vec2vec paper"
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
license-files = ["LICEN[CS]E*"]
dependencies = [
    "numpy>=2.4.4",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
    "tqdm>=4.67.3",
]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "mkdocstrings-python>=2.0.3",
    "pytest>=9.0.3",
    "sentence-transformers>=5.5.1",
    "torch>=2.12.0",
    "zensical>=0.0.43",
]

[project.urls]
Repository = "https://github.com/sw241395/mini-vec2vec"
Documentation = "https://sw241395.github.io/mini-vec2vec/"

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"
